- hosts: local
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      become: true

    - name: Pull Docker Image
      docker_image:
        name: gv2002/scientific-calculator
        source: pull

    - name: Run Calculator Container
      name: scientific-calculator
      shell: docker run -it -d --name sc-calculator gv2002/scientific-calculator
