- hosts: local
  tasks:
    - name: Ensure Docker SDK for Python is installed
      pip:
        name: docker
        state: present

    - name: Pull Docker Image
      docker_image:
        name: gv2002/scientific-calculator
        source: pull

    - name: Run Calculator Container
      shell: docker run -it -d --name sc-calculator gv2002/scientific-calculator
